'use strict';
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="detail-v2.css?v=20260822-free-reason-v2">');
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="virtual-score.css">');
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="strategy-compare.css">');
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="mobile-tap.css">');
const $=s=>document.querySelector(s);let currentPage='upcoming',todayData={date:null,races:[]},resultSelectedDate=null,resultDayData=null,cumulativeData={},historyIndex={available_dates:[]},resultRequestSerial=0,resultAbortController=null,explicitTab=false,vpDailyTab='LINE',vpCumTab='LINE',vpPeriod='DAYS_7',suppressDetailCloseHistory=false;let today=todayData,dayData=resultDayData,index=historyIndex,cumulative=cumulativeData,page=currentPage,selectedDate=resultSelectedDate;
const esc=x=>String(x??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),pct=x=>x==null?'—':`${(Number(x)*100).toFixed(1)}%`,tm=r=>new Date(r.start_time).toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'}),yen=n=>Number(n||0).toLocaleString()+'円',lineup=r=>(r?.lineup||[]).map(x=>x.join('-')).join(' / '),grade=(n,g)=>`<strong class="grade g${g}">${n??'—'} ${g??''}</strong>`;
const lines=r=>[...(r?.line_model?.lines||[])].sort((a,b)=>b.line_event_share-a.line_event_share),third=(r,e)=>r?.line_model?.lines?.find(x=>x.event===e)?.third_candidates||r?.line_model?.third_distribution_vnext?.lines?.find(x=>x.event===e)?.candidates||[],flow=r=>r?.race_flow_display?.viewer_narrative||r?.race_flow_display?.narrative||'展開コメントなし';
const ticketBuy=(candidate,model)=>candidate?.ticket_buy_v3?.model===model?candidate.ticket_buy_v3:null;
const share=x=>x==null?'—':`${(Number(x)*100).toFixed(1)}%`;
const qualification=v=>v?.eligibility?.race_prediction?.status==='PROSPECTIVE_VALID'?'✓ 発走前に確定した予想で検証':'参考表示：発走後に追加された内容は正式成績に含めていません',price=s=>({CLEARLY_INSUFFICIENT:'この価格では買いづらい',INSUFFICIENT:'価格が少し足りない',BORDERLINE:'価格はほぼ見合う',PRICE_SUPPORTED:'買える価格',STRONG_PRICE:'かなり価格に余裕あり'}[s]||'価格判定なし');
function raceCard(r){if(r.quality_status!=='PREDICTION_FROZEN'){const reason=r.prediction?.reasons?.[0]||'NOT_PROCESSED';return`<article class="race-card incomplete tappable" data-race="${r.id}" role="button" tabindex="0" aria-label="${esc(r.venue)}${r.race_no}Rの停止理由を見る"><div class="head"><b>${r.venue} ${r.race_no}R</b><time>${tm(r)}</time></div><div class="scores"><div><small>現在版</small><strong>予想未確定</strong></div></div><p>${esc(stopReason(reason))}</p><small class="detail-cue">停止理由を見る →</small></article>`}const l=lines(r)[0],f=(r.free_model?.top12||[]).slice(0,3);return`<article class="race-card tappable" data-race="${r.id}" role="button" tabindex="0" aria-label="${esc(r.venue)}${r.race_no}Rの予想詳細を見る"><div class="head"><b>${r.venue} ${r.race_no}R</b><time>${tm(r)}</time></div><div class="scores"><div><small>PURE</small>${grade(r.pure_score,r.pure_grade)}</div><div><small>レース買い度</small>${grade(r.buy_score,r.buy_grade)}</div></div><p>並び ${lineup(r)}</p><div class="quick"><b>LINE ${l?.event} ${pct(l?.line_event_share)}</b><span>3着 ${third(r,l?.event).slice(0,3).map(x=>x.third).join(' / ')}</span><b>FREE ${f.map(x=>x.trifecta).join(' / ')}</b></div><small class="detail-cue">詳細を見る →</small></article>`}
const stopReason=x=>{const s=String(x||'');if(s==='PREDICTION_CUTOFF_EXPIRED')return'予想締切を過ぎたため正式予想は作成していません。';if(s==='STOP_RETRYABLE_LINEUP_UNKNOWN')return'並びを確認できていないため、まだ予想を確定していません。';if(s==='LINEUP_CONFLICT'||s.startsWith('LINEUP_'))return'並び情報を確認できなかったため、予想を止めています。';if(s.startsWith('FULL_GATE:')||s.includes('PREDICTABILITY_COMPONENT_INCOMPLETE'))return'必要な予測台帳が揃わなかったため停止しています。';return({NOT_SELECTED_TEST_LIMIT:'この時点ではテスト対象外だったため、まだ予想は確定していません。',NOT_PROCESSED:'まだ予想処理が行われていません。',LEGACY_MODEL_ONLY:'旧モデルの予想だけが残っています。現在の正式検証対象には含めていません。',CURRENT_PRODUCTION_INCOMPLETE:'現在版の予想は、必要な情報が揃っていないため未確定です。',FAILED_TEST_ONLY:'試験用の記録だけが残っています。正式な予想としては表示していません。'}[s]||'必要な情報が揃わなかったため、予想を確定していません。')};
const carMark=n=>['','①','②','③','④','⑤','⑥','⑦'][Number(n)]||esc(n);
const referenceBuyHtml=x=>{const b=x?.reference_buy;if(!b)return'<small>参考BUY 未算出</small>';return`<small>${b.odds==null?'オッズ未取得':b.odds+'倍'}</small><strong>参考うまみ度 ${b.score??'—'} ${b.grade||''}</strong>`};
function predictionLineCards(r){return lines(r).map((l,i)=>`<article class="line-card ${i?'':'favorite'}"><header><small>${i?'LINE #'+(i+1):'本命LINE'}</small><h3>${esc(l.event).replace('-',' → ')}</h3><b>未校正LINEシェア ${share(l.line_event_share)}</b></header><div class="metrics"><span>展開<b>${l.line_advantage_score??'—'}</b></span><span>実力<b>${l.line_strength_score??'—'}</b></span><span>番手追走<b>${l.second_rider_follow_likelihood??'—'}</b></span></div><h4>3着ランキング</h4><p class="sub">上位2車がこの順で来た場合の、3着候補5人のAI評価を100%に配分した値です。</p><div class="third-detail">${third(r,l.event).map(x=>`<div class="third-ticket"><span>#${x.rank} ${carMark(x.third)}</span><b>3着評価シェア ${share(x.uncalibrated_share??x.conditional_estimate)}</b><small>${x.combination||`${l.event}-${x.third}`}</small>${referenceBuyHtml(x)}</div>`).join('')}</div></article>`).join('')}
function freeSelectionNarrative(r){
  const top=(r?.free_model?.top12||[]).map(x=>({...x,parts:String(x.trifecta||'').split('-').map(Number)})).filter(x=>x.parts.length===3&&x.parts.every(Number.isFinite));
  if(!top.length)return'このレースは、FREE Top12の選定理由を表示できる発走前データがありません。';
  const countBy=(key)=>{const m=new Map;top.forEach(x=>{const k=key(x);m.set(k,(m.get(k)||0)+1)});return[...m].sort((a,b)=>b[1]-a[1]||String(a[0]).localeCompare(String(b[0])))};
  const first=countBy(x=>x.parts[0]),pairs=countBy(x=>`${x.parts[0]}-${x.parts[1]}`),head=Number(first[0][0]),center=pairs[0][0].split('-').map(Number),pairTickets=top.filter(x=>x.parts[0]===center[0]&&x.parts[1]===center[1]),thirds=[...new Set(pairTickets.map(x=>x.parts[2]))];
  const units=r?.lineup||[],unitOf=n=>units.find(u=>u.map(Number).includes(Number(n)))||[],roleOf=n=>{const u=unitOf(n),i=u.map(Number).indexOf(Number(n));return{unit:u.map(Number),index:i,label:u.length===1?'単騎':i===0?'ライン先頭':i===1?'番手':'3番手以降'}};
  const flow3=r?.race_flow_display?.narrative_v3_structure||null,initial=flow3?.initial_order||[],transition=flow3?.transition_order||[],positions=flow3?.final_position_by_rider||{},conflict=flow3?.initiative_conflict_assessment||null;
  if(!flow3||!initial.length||!transition.length||!Object.keys(positions).length||!conflict)return'具体的な隊列変化が発走前データに保存されていないため、FREE Top12の選定理由は表示していません。';
  const orderText=x=>x.map(u=>u.join('-')).join(' / '),positionOf=n=>Number(positions[String(n)])||null,positionText=n=>positionOf(n)?`${positionOf(n)}番手`:'位置未保存';
  const scenarioEvent=key=>{const s=String(r?.scenarios?.[key]?.summary||''),m=s.match(/([1-7])\s*[-→]\s*([1-7])/);return m?[Number(m[1]),Number(m[2])]:null},main=scenarioEvent('MAIN'),alt=scenarioEvent('ALTERNATIVE');
  const format=String(r?.formation||'').split('-').filter(Boolean).map(Number),formationText=format.length?`${format.map((n,i)=>n===1?'単騎':`${n}車ライン`).join('・')}に分かれる形`:'この並び';
  const headRole=roleOf(head),centerFirstRole=roleOf(center[0]),centerSecondRole=roleOf(center[1]),sentences=[];
  if(flow3&&initial.length&&transition.length)sentences.push(`${formationText}で、初手は${orderText(initial)}、上昇後は${orderText(transition)}を本線にしている。${flow3.front_line_action==='STAY_FRONT'?'前受け側が突っ張る':'前受け側が一回出す'}流れで、主導権争いは${conflict?.level==='HIGH'?'長くなりやすい':conflict?.level==='LOW'?'長引きにくい':'一度ぶつかっても長い踏み合いまでは見ていない'}。`);
  if(main&&head===main[0])sentences.push(`MAINでは${main[0]}-${main[1]}を中心にしており、${carMark(head)}は${positionText(head)}から仕掛ける読み。そこから先頭まで届く形を見て、FREEでは${carMark(head)}を主要な1着候補にした。`);
  else if(alt&&head===alt[0])sentences.push(`${formationText}で、MAINだけでなく${alt[0]}-${alt[1]}が先に仕掛ける別の流れも重く見ている。その形なら${carMark(head)}が前を飲み込むところまであり、FREEでは${carMark(head)}を主要な1着候補にした。`);
  else if(headRole.index===1){const leader=headRole.unit[0],leaderPos=positionText(leader);sentences.push(`${headRole.unit.join('-')}の先頭${carMark(leader)}が${leaderPos}から仕掛けて脚を使い、その後ろの${carMark(head)}が直線で交わす形まで見ている。だから番手の${carMark(head)}も主要な1着候補にした。`);}
  else sentences.push(`${formationText}で、MAINの${main?main.join('-'):'中心ライン'}が動いた後の位置取りまで考えると、${headRole.label}の${carMark(head)}が最後に一番伸びる形を上位に置いた。`);
  const sameUnit=centerFirstRole.unit.length&&centerFirstRole.unit.join('-')===centerSecondRole.unit.join('-');
  if(sameUnit&&centerFirstRole.index===0&&centerSecondRole.index===1)sentences.push(`中心の1・2着は${center[0]}→${center[1]}。${carMark(center[0])}が出切り、番手の${carMark(center[1])}も離れず続く形が一番素直なので、この並びを軸にしている。`);
  else if(sameUnit&&centerFirstRole.index===1&&centerSecondRole.index===0)sentences.push(`中心の1・2着は${center[0]}→${center[1]}。${carMark(center[1])}が前で脚を使い、番手の${carMark(center[0])}が直線で交わすところまで見た番手差しの形だ。`);
  else if(sameUnit)sentences.push(`中心の1・2着は${center[0]}→${center[1]}。同じ${centerFirstRole.unit.join('-')}の中でも番手まで順番どおりに残るとは限らず、直線の伸びでこの順になると見ている。`);
  else {const secondPath=centerSecondRole.unit.length===1?`単騎の${carMark(center[1])}が${positionText(center[1])}から直線で伸びる`:`${centerSecondRole.unit.join('-')}の${centerSecondRole.label} ${carMark(center[1])}が${positionText(center[1])}から食い込む`;sentences.push(`中心の1・2着は${center[0]}→${center[1]}。${carMark(center[0])}が先に届き、${secondPath}混成決着を上に取った。`);}
  const thirdRoles=[...new Set(thirds.map(n=>roleOf(n).label))],thirdMarks=thirds.map(carMark).join('・');
  if(thirds.length>1)sentences.push(`3着は${thirdMarks}まで残した。${thirds.map(n=>`${carMark(n)}は${positionText(n)}`).join('、')}で、仕掛けたラインの残りと、脚を残して直線へ入る選手の差を大きく見ていないため、一人には絞っていない。`);
  else sentences.push(`3着は${thirdMarks}を上に取った。中心の1・2着が決まった後の位置関係では、この選手が一番残りやすいと見ている。`);
  const favorite=lines(r)[0]?.event,centerEvent=center.join('-');
  if(favorite&&favorite!==centerEvent){const f=favorite.split('-').map(Number),relation=f[0]===center[0]?'1着候補は同じだが2着が入れ替わる':'1着から別の形',secondPath=centerSecondRole.unit.length===1?`単騎の${carMark(center[1])}が${positionText(center[1])}から直線で伸びる形`:centerSecondRole.index===0?`${centerSecondRole.unit.join('-')}の先頭${carMark(center[1])}が${positionText(center[1])}まで残る形`:`${centerSecondRole.unit.join('-')}の${centerSecondRole.label} ${carMark(center[1])}が${positionText(center[1])}から食い込む形`;sentences.push(`LINE本命は${favorite.replace('-','→')}だが、FREEの中心は${centerEvent.replace('-','→')}で、${relation}。LINEは先頭から番手まで残る形を比べる一方、FREEでは${secondPath}を取り、ラインが崩れる決着を上に置いた。`)}
  else if(favorite)sentences.push(`LINE本命の${favorite.replace('-','→')}とFREEの中心は一致している。ただFREEでは、その1・2着だけで決め打ちせず、ALTで隊列が崩れた場合の着順もTop12に残している。`);
  const altInTop=alt&&top.some(x=>x.parts[0]===alt[0]&&x.parts[1]===alt[1]);
  if(alt)sentences.push(`${altInTop?`ALTの${alt[0]}→${alt[1]}も、先に仕掛けてそのまま残る場合として押さえた。`:`ALTでは${alt[0]}-${alt[1]}が先に動く流れも見ているが、そのラインが1・2着までそのまま残る形は上位に取らなかった。`}MAINの残り方と、この別展開で前後が入れ替わる形を合わせたものが今回のTop12だ。`);
  else sentences.push(`MAINどおりに先頭と番手が残る形だけでなく、仕掛けの後に2着・3着が入れ替わる形まで合わせたものが今回のTop12だ。`);
  return sentences.slice(0,6).join('');
}
function openPredictionDetail(r,{updateUrl=true}={}){
  if(r.quality_status!=='PREDICTION_FROZEN'){const reasons=r.prediction?.reasons||['NOT_PROCESSED'];$('#detailBody').innerHTML=`<section class="detail-section prediction-summary"><h1>${esc(r.venue)}${r.race_no}R　${tm(r)}</h1><h2>このレースはまだ予想確定前です</h2>${reasons.map(x=>`<p>${esc(stopReason(x))}</p>`).join('')}</section>`;if(!$('#detail').open)$('#detail').showModal();if(updateUrl)history.pushState({page:'upcoming',race:String(r.id)},'',`${location.pathname}?race=${encodeURIComponent(r.id)}`);return;}
  const fit=r.development_fit?.ranking||[],free=r.free_model?.top12||[],p=r.prediction||{};
  $('#detailBody').innerHTML=`<section class="detail-section prediction-summary"><small>発走前Prediction</small><h1>${esc(r.venue)}${r.race_no}R　${tm(r)}</h1><div class="fact-grid"><span>並び <b>${lineup(r)||'—'}</b></span><span>型 <b>${r.formation||'—'}</b></span><span>PURE <b>${r.pure_score??'—'} ${r.pure_grade||''}</b></span><span>レース買い度 <b>${r.buy_score??'—'} ${r.buy_grade||''}</b></span><span>読みやすさ <b>${r.race_predictability_score??'—'}</b></span><span>予想確定 <b>${p.freeze_timestamp?new Date(p.freeze_timestamp).toLocaleString('ja-JP'):'—'}</b></span><span>version <b>${esc(p.version||'—')}</b></span><span>正式BUY <b>校正待ち</b></span></div></section><section class="detail-section flow-v2"><h2>AI展開予想</h2><p>${esc(flow(r))}</p></section>${strengthResearchHtml(r)}<section class="detail-section fit-detail"><h2>展開有利LINEランキング</h2>${fit.length?fit.map(x=>`<article class="fit-row ${x.rank===1?'fit-top':''}"><b>#${x.rank} ${esc(x.event).replace('-',' → ')}</b><strong>${x.line_development_fit_score??'—'}</strong><small>根拠の揃い具合 ${x.coverage==null?'—':Math.round(x.coverage*100)+'%'}</small></article>`).join(''):'<p>保存なし</p>'}</section><section class="detail-section line-detail"><h2>LINE MODEL</h2><p>数値は校正前の相対順位です。確率ではありません。</p><div class="line-grid">${predictionLineCards(r)}</div></section><section class="detail-section free-detail"><h2>FREE MODEL Top12</h2><p>全210通りのAI評価を100%に配分したランキングです。</p><aside class="free-selection-reason"><small>発走前のFREE評価だけで整理</small><h3>この12点を選んだ理由</h3><p>${esc(freeSelectionNarrative(r))}</p></aside><div class="free-detail-list">${free.map(x=>`<article><b>#${x.rank}</b><strong>${x.trifecta}</strong><span>全体評価シェア ${share(x.uncalibrated_share)}</span><small>${esc(x.scenario_relation||'')}</small>${referenceBuyHtml(x)}</article>`).join('')}</div></section><section class="detail-section reference-buy-note"><h2>参考BUY</h2><p>未校正のAI評価と現在オッズを比較した参考値です。正式BUYは校正待ちです。</p></section>`;if(!$('#detail').open)$('#detail').showModal();if(updateUrl)history.pushState({page:'upcoming',race:String(r.id)},'',`${location.pathname}?race=${encodeURIComponent(r.id)}`);
}
function strengthResearchHtml(r){const s=r.rider_strength_research;if(!s)return'';return`<details class="detail-section"><summary><b>研究モード：選手評価</b></summary><p>正式Prediction・BUYには未接続のShadow評価です。</p><div class="strength-map">${s.riders.map(x=>`<article><b>${carMark(x.rider_number)} ${esc(x.tier)}</b><span>総合 ${x.overall.score??'—'} / 1着 ${x.first.score??'—'} / 2着 ${x.second.score??'—'} / 3着 ${x.third.score??'—'}</span><small>${esc(x.reason)}</small></article>`).join('')}</div></details>`}
function resultCard(v,r){const fr=v.free.prospective_original_top12.rank,actual=v.actual.trifecta,top=r?.free_model?.top12?.[0]?.trifecta,actualLine=v.line.actual_line_event||`${v.actual.first}-${v.actual.second}`,freeResult=fr===1?`🎯 予想 #1 ${actual} / 実際 ${actual}`:fr?`✅ 実際 ${actual} は予想 #${fr}`:`❌ 予想 #1 ${top||'—'} / 実際 ${actual} Top12外`;return`<article class="result-card" data-result="${v.race_id}"><div class="head"><b>${r?.venue} ${r?.race_no}R</b><time>${r?tm(r):'—'}</time></div><div class="actual"><strong>結果 ${actual}</strong><b>3連単 ${yen(v.actual.payout)}</b></div><div class="answer-mini"><p><b>LINE</b> ${v.line.favorite_hit?`✅ ${v.line.favorite.replace('-','→')} 的中`:`❌ 予想 ${v.line.favorite.replace('-','→')} / 実際 ${actualLine.replace('-','→')}`}</p><p><b>FREE</b> ${freeResult}</p></div><small class="human-status">${qualification(v)}</small><button class="more">詳しく見る</button></article>`}
const statPct=x=>x==null?'—':(x*100).toFixed(1)+'%',statYen=x=>(Number(x)||0).toLocaleString()+'円';function virtualPurchaseView(){const x=dayData?.virtual_purchase;if(!x)return'<section class="virtual-score"><h2>仮想購入成績</h2><p>この日の派生成績はまだ作成されていません。</p></section>';const card=(name,s,rule)=>`<article><small>${name}</small><h3>的中 ${s.hits} / ${s.eligible_races}R　${statPct(s.hit_rate)}</h3><div><span>投資 <b>${statYen(s.stake)}</b></span><span>払戻 <b>${statYen(s.return)}</b></span><span>収支 <b class="${s.profit>=0?'plus':'minus'}">${s.profit>=0?'+':''}${statYen(s.profit)}</b></span><span>回収率 <b>${statPct(s.recovery_rate)}</b></span></div><p>${rule}</p></article>`;const jstToday=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo'}).format(new Date());return`<section class="virtual-score"><header><div><small>100円均等・モデル比較用</small><h2>${selectedDate===jstToday?'今日':'この日'}の仮想成績</h2></div><b>${x.validated_results}R 結果確定</b></header><div class="virtual-grid">${card('LINE 3点買い',x.line,'本命LINEの3着予想上位3点を各100円')}${card('FREE 12点買い',x.free,'発走前FREE Top12を各100円')}</div><small>実際の購入履歴ではありません。発走前に確定した予想だけを集計しています。</small></section>`}
const vpOrders={LINE:['MAIN_LINE_TOP1','MAIN_LINE_TOP3','MAIN_LINE_TOP5','TOP2_LINES_TOP1','TOP2_LINES_TOP3','TOP2_LINES_TOP5','DEV_LINE_TOP1','DEV_LINE_TOP3','DEV_LINE_TOP5'],FREE:['FREE_TOP1','FREE_TOP3','FREE_TOP5','FREE_TOP8','FREE_TOP12']};
const vpMainCard=(name,s,rule)=>`<article><small>${name}</small><h3>的中 ${s.hit_races} / ${s.eligible_races}R　${statPct(s.hit_rate)}</h3><div><span>投資 <b>${statYen(s.investment)}</b></span><span>払戻 <b>${statYen(s.payout)}</b></span><span>収支 <b class="${s.profit>=0?'plus':'minus'}">${s.profit>=0?'+':''}${statYen(s.profit)}</b></span><span>回収率 <b>${statPct(s.recovery_rate)}</b></span></div><p>${rule}</p></article>`;
function vpComparison(strategies,tab,scope){const ids=vpOrders[tab],rows=ids.map((id,i)=>{const s=strategies?.[id];if(!s)return'';const prior=i&&strategies?.[ids[i-1]],dh=prior&&s.hit_rate!=null&&prior.hit_rate!=null?(s.hit_rate-prior.hit_rate)*100:null,dr=prior&&s.recovery_rate!=null&&prior.recovery_rate!=null?(s.recovery_rate-prior.recovery_rate)*100:null;return`<div class="vp-row ${s.main?'main':''}"><b>${s.label}${s.main?' ★':''}</b><span>対象 ${s.eligible_races}R</span><span>的中 ${s.hit_races} / ${statPct(s.hit_rate)}</span><span>回収 ${statPct(s.recovery_rate)}</span><span>収支 ${s.profit>=0?'+':''}${statYen(s.profit)}</span>${prior?`<small>前行比：的中率 ${dh==null?'—':(dh>=0?'+':'')+dh.toFixed(1)+'pt'} / 回収率 ${dr==null?'—':(dr>=0?'+':'')+dr.toFixed(1)+'pt'}</small>`:''}</div>`}).join('');return`<section class="vp-compare"><h2>他の買い方を比較</h2><div class="vp-tabs"><button class="${tab==='LINE'?'active':''}" onclick="setVpTab('${scope}','LINE')">LINE</button><button class="${tab==='FREE'?'active':''}" onclick="setVpTab('${scope}','FREE')">FREE</button></div><div>${rows}</div><small>100円均等の実績値です。「最適」を示すものではありません。</small></section>`}
function setVpTab(scope,tab){if(scope==='daily'){vpDailyTab=tab;renderResults()}else{vpCumTab=tab;$('#content').innerHTML=cumulativeView()}}
function setVpPeriod(period){vpPeriod=period;$('#content').innerHTML=cumulativeView()}
function virtualPurchaseViewV2(){if(currentPage!=='results'||!resultDayData||resultDayData.date!==resultSelectedDate)return'';const x=resultDayData.virtual_purchase;if(!x?.strategies)return'';const jstToday=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo'}).format(new Date()),line=x.strategies.MAIN_LINE_TOP3,free=x.strategies.FREE_TOP12;return`<section class="virtual-score"><header><div><small>100円均等・モデル比較用</small><h2>${resultSelectedDate===jstToday?'今日':'この日'}の仮想成績</h2></div><b>${x.validated_results}R 結果確定</b></header><div class="virtual-grid">${vpMainCard('LINE 本命3点',line,'本命LINEの3着予想上位3点を各100円')}${vpMainCard('FREE Top12',free,'発走前FREE Top12を各100円')}</div><small>実際の購入履歴ではありません。発走前に確定した予想だけを集計しています。</small></section>${vpComparison(x.strategies,vpDailyTab,'daily')}`};virtualPurchaseView=virtualPurchaseViewV2;
function lineAnswer(r,a){return`<section class="answer-section"><h2>⑤ LINE MODEL 答え合わせ</h2><p class="sub">発走前に見ていた全ラインです。実際の1・2着と同じ形を強調しています。</p><div class="line-grid">${lines(r).map((l,i)=>{const hit=l.event===`${a.first}-${a.second}`;return`<article class="line-card ${i?'':'favorite'} ${hit?'hit':''}"><header><small>${i?'予想 #'+(i+1):'予想本命'} ${hit?'✅ 実際に成立':''}</small><h3>${l.event.replace('-',' → ')}</h3><b>成立推定 ${pct(l.line_event_share)}</b></header><div class="third-answer">${third(r,l.event).map((x,j)=>{const t=ticketBuy(x,'LINE_MODEL');return`<div class="${hit&&x.third===a.third?'hit-third':''}"><b>#${j+1} ③${x.third}</b><span>${pct(x.conditional_estimate)}</span><span>${t?.odds!=null?t.odds+'倍':'オッズ未取得'}</span><strong>${t?.score!=null?'うまみ度 '+t.score+' '+(t.grade||''):'LINE BUY 未算出'}</strong>${hit&&x.third===a.third?'<em>✅ 実際の3着</em>':''}</div>`}).join('')}</div></article>`}).join('')}</div></section>`}
function freeAnswer(r,a,v){const xs=r.free_model?.top12||[],hit=xs.find(x=>x.trifecta===a.trifecta),rank210=v?.free?.full_210_v2?.rank??hit?.rank??null,band=rank210===1?'Top1':rank210<=3?'Top3':rank210<=5?'Top5':rank210<=12?'Top12':rank210?'Top12外':'順位未保存',mark=rank210===1?'🎯':rank210&&rank210<=12?'✅':'❌';return`<section class="answer-section"><h2>⑥ FREE MODEL 答え合わせ</h2><div class="answer-callout">${mark} 実着 ${a.trifecta}　${rank210?`FREE #${rank210} / 210・${band}`:band}</div><div class="free-list">${xs.map(x=>`<div class="free ${x===hit?'hit':''}"><span>#${x.rank}</span><b>${x.trifecta}</b><strong>${pct(x.model_probability_uncalibrated)}</strong>${x===hit?'<em>✅ 実着</em>':''}</div>`).join('')}</div></section>`}
function buyAnswer(r,a){return`<section class="answer-section"><h2>⑦ BUY答え合わせ</h2><p class="sub">発走前に保存されていたFREE用オッズとうまみ度です。</p><div class="buy-answer">${(r.free_model?.top12||[]).map(x=>{const t=ticketBuy(x,'FREE_ORDER_MODEL')||{},hit=x.trifecta===a.trifecta;return`<div class="${hit?'hit':''}"><b>${x.trifecta}</b><span>${pct(x.model_probability_uncalibrated)}</span><span>${t.odds!=null?t.odds+'倍':'オッズ未取得'}</span><span>${price(t.price_status)}</span><strong>${t.score!=null?'うまみ度 '+t.score+' '+(t.grade||''):'FREE BUY 未算出'}</strong><em>${hit?'✅ 的中':'外れ'}</em></div>`}).join('')}</div></section>`}
function openResult(v,r){const fit=r.development_fit?.ranking||[],d=v.development_fit;$('#detailBody').innerHTML=`<div class="actual big"><small>① 実際の結果</small><strong>結果 ${v.actual.trifecta}</strong><b>3連単 ${yen(v.actual.payout)}</b></div><section class="answer-section before-facts"><h2>② 予想時の基本情報</h2><div class="fact-grid"><span>PURE ${r.pure_score??'—'} ${r.pure_grade||''}</span><span>レース買い度 ${r.buy_score??'—'} ${r.buy_grade||''}</span><span>読みやすさ ${r.race_predictability_score??'—'}</span><span>並び ${lineup(r)}</span><span>型 ${r.formation}</span><span>Market ${r.market?.observed_at?new Date(r.market.observed_at).toLocaleString('ja-JP'):'未取得'}</span></div><small>${qualification(v)}</small></section><section class="flow"><h2>③ 予想時のAI展開</h2><p>${esc(flow(r))}</p><small>実際の結果と見比べて答え合わせ</small></section><section class="answer-section"><h2>④ 展開向きライン</h2><div class="fit-ranking">${fit.map(x=>`<div><b>#${x.rank} ${x.event}</b><span>${x.line_development_fit_score}</span>${x.rank===1?`<em>${d.line_hit?'✅ LINE成立':'❌ LINE不成立'} / ${d.leader_won?'先頭1着':d.leader_top2?'先頭連対':'先頭連対なし'}</em>`:''}</div>`).join('')}</div></section>${lineAnswer(r,v.actual)}${freeAnswer(r,v.actual,v)}${buyAnswer(r,v.actual)}<div class="eligibility-box"><b>${qualification(v)}</b></div>`;$('#detail').showModal();history.replaceState(null,'',`?date=${selectedDate}&race=${encodeURIComponent(v.race_id)}`)}
const detailBack=()=>`<button class="back-results" type="button">← 結果一覧へ</button>`;
const modelNote=(v,key)=>v?.eligibility?.[key]?.status==='PROSPECTIVE_VALID'?'✓ 発走前に確定した記録':'参考：発走後に追加されたモデルのため正式成績には含めていません';
function resultSummary(v){const fr=v.free.prospective_original_top12.rank;return`<div class="result-verdict"><b>LINE ${v.line.favorite_hit?'✅ 的中':'❌ 外れ'}</b><b>FREE ${fr===1?'🎯 #1':fr?`✅ #${fr}`:'❌ Top12外'}</b></div>`}
function flowFacts(v){const f=v.race_flow||{},row=(label,pred,actual)=>`<div><b>${label}</b><span>予想 ${pred??'保存なし'}</span><span>実際 ${actual?.length?actual.join('・'):'確認できず'}</span></div>`;return`<section class="detail-section flow-compare"><h2>実際はどうなった？</h2>${row('S','保存なし',f.actual_S)}${row('H','保存なし',f.actual_H)}${row('B','保存なし',f.actual_B)}<p class="data-note">結果sourceで確認できた事実だけを表示しています。</p></section>`}
function fitDetail(r,v){const xs=r.development_fit?.ranking||[],d=v.development_fit||{},reason=r.development_fit?.top_summary?.reason;return`<section class="detail-section fit-detail"><h2>展開が向くと見ていたライン</h2>${xs.map((x,i)=>`<article class="fit-row ${i?'':'fit-top'}"><b>${i?'#'+x.rank:'🥇'} ${x.event.replace('-',' → ')}</b><strong>${x.line_development_fit_score}</strong>${i===0&&reason?`<p>${esc(reason)}</p>`:''}</article>`).join('')}<div class="validation-strip"><span>1位LINE成立 ${d.line_hit?'✅':'❌'}</span><span>先頭1着 ${d.leader_won?'✅':'❌'}</span><span>先頭2着内 ${d.leader_top2?'✅':'❌'}</span><span>H/B ${d.actual_H?.length||d.actual_B?.length?'確認あり':'確認できず'}</span></div><small>${modelNote(v,'development_fit_vnext')}</small></section>`}
function lineDetail(r,v){const actualEvent=`${v.actual.first}-${v.actual.second}`;return`<section class="detail-section line-detail"><h2>LINE MODEL — 予想と結果</h2><p>本命だけでなく、発走前に残していた全ラインです。</p><div class="line-grid">${lines(r).map((l,i)=>{const hit=l.event===actualEvent;return`<article class="line-card ${i?'':'favorite'} ${hit?'actual-hit':''}"><header><small>${i?'LINE #'+(i+1):'本命LINE'} ${hit?'・実際に成立 ✅':''}</small><h3>${l.event.replace('-',' → ')}</h3><b>成立推定 ${pct(l.line_event_share)}</b></header><div class="metrics"><span>展開<b>${l.line_advantage_score??'—'}</b></span><span>実力<b>${l.line_strength_score??'—'}</b></span><span>番手追走<b>${l.second_rider_follow_likelihood??'—'}</b></span></div><h4>3着予想</h4><div class="third-detail">${third(r,l.event).map((x,j)=>{const t=ticketBuy(x,'LINE_MODEL'),actual=hit&&x.third===v.actual.third;return`<div class="third-ticket ${actual?'actual-hit':''}"><span>#${j+1} ③${x.third}${actual?' ✅ 実3着':''}</span><b>${pct(x.conditional_estimate)}</b><small>${x.combination||`${l.event}-${x.third}`}</small><small>${t?.odds!=null?t.odds+'倍':'当時のオッズなし'}</small><strong>${t?.score!=null?'LINEうまみ度 '+t.score+' '+(t.grade||''):'LINE BUY 当時のデータなし'}</strong></div>`}).join('')}</div></article>`}).join('')}</div><small>${modelNote(v,'race_prediction')}</small></section>`}
function freeDetail(r,v){const xs=r.free_model?.top12||[],rank=v.free?.full_210_v2?.rank??null,preRank=v.free?.prospective_original_top12?.rank??null,actual=v.actual.trifecta,band=preRank===1?'🎯 #1的中':preRank<=3&&preRank?'✅ Top3':preRank<=5&&preRank?'✅ Top5':preRank<=12&&preRank?'✅ Top12':'❌ Top12外';return`<section class="detail-section free-detail"><h2>FREE MODEL — Top12答え合わせ</h2><aside class="free-selection-reason"><small>発走前のFREE評価だけで整理</small><h3>この12点を選んだ理由</h3><p>${esc(freeSelectionNarrative(r))}</p></aside><div class="free-verdict"><b>発走前の予想：${band}</b><span>実着 ${actual}</span><strong>${rank?`参考構造では全210通り中 #${rank}`:'全210順位は当時のデータなし'}</strong></div><div class="free-detail-list">${xs.map(x=>{const t=ticketBuy(x,'FREE_ORDER_MODEL'),hit=x.trifecta===actual;return`<article class="${hit?'actual-hit':''}"><b>#${x.rank}</b><strong>${x.trifecta}${hit?' ← 実際の結果 ✅':''}</strong><span>${pct(x.model_probability_uncalibrated)}</span><small>${t?.odds!=null?t.odds+'倍':'当時のオッズなし'}</small><small>${t?.score!=null?'FREEうまみ度 '+t.score+' '+(t.grade||''):'FREE BUY 当時のデータなし'}</small></article>`}).join('')}</div><small>${modelNote(v,'free_probability_v2_0')}</small></section>`}
function buyRows(r,v,model){const actual=v.actual.trifecta,source=model==='LINE_MODEL'?lines(r).flatMap(l=>third(r,l.event)):r.free_model?.top12||[];return source.map(x=>{const combination=x.combination||x.trifecta,t=ticketBuy(x,model),hit=combination===actual,p=model==='LINE_MODEL'?lines(r).find(l=>combination.startsWith(l.event+'-'))?.line_event_share*x.conditional_estimate:x.model_probability_uncalibrated;return`<article class="buy-row ${hit?'actual-hit':''}"><b>${combination}</b><span>${model==='LINE_MODEL'?'LINE':'FREE'}</span><span>AI推定 ${pct(p)}</span><span>${t?.odds!=null?t.odds+'倍':'当時のオッズなし'}</span><span>比率 ${t?.price_ratio?.toFixed?.(2)??'—'}</span><span>${price(t?.price_status)}</span><strong>${t?.score!=null?'うまみ度 '+t.score+' '+(t.grade||''):'当時のBUYデータなし'}</strong><em>${hit?'✅ 的中':'外れ'}</em></article>`}).join('')}
function actualTicketDetail(r,v){const a=v.actual.trifecta,full=v.free?.full_210_v2||{},pre=v.free?.prospective_original_top12||{},line=lines(r).find(l=>l.event===`${v.actual.first}-${v.actual.second}`),thirdHit=line&&third(r,line.event).find(x=>x.third===v.actual.third),lineBuy=thirdHit&&ticketBuy(thirdHit,'LINE_MODEL'),freeHit=(r.free_model?.top12||[]).find(x=>x.trifecta===a),freeBuy=freeHit&&ticketBuy(freeHit,'FREE_ORDER_MODEL');return`<section class="detail-section actual-ticket"><h2>AIはこの車券をどう見ていた？</h2><h3>${a}</h3><div class="actual-ticket-grid"><article><b>FREE</b><span>発走前Top12 ${pre.rank?'#'+pre.rank:'圏外'}</span><span>${full.rank?`参考構造 #${full.rank} / 210`:'全210順位なし'}</span><span>参考AI推定 ${pct(full.probability)}</span></article><article><b>LINE</b><span>${line?`${line.event.replace('-','→')}はLINE #${lines(r).indexOf(line)+1}`:'該当LINEなし'}</span><span>${thirdHit?`3着③${thirdHit.third}は #${third(r,line.event).indexOf(thirdHit)+1}`:'3着順位なし'}</span></article><article><b>Market / BUY</b><span>LINE ${lineBuy?.odds!=null?lineBuy.odds+'倍':'当時のデータなし'} / ${lineBuy?.score!=null?lineBuy.score+(lineBuy.grade||''):'未算出'}</span><span>FREE ${freeBuy?.odds!=null?freeBuy.odds+'倍':'当時のデータなし'} / ${freeBuy?.score!=null?freeBuy.score+(freeBuy.grade||''):'未算出'}</span></article></div></section>`}
function readSummary(v){const l=v.line,fr=v.free.prospective_original_top12.rank,parts=[];if(l.favorite_hit)parts.push(`本命LINE ${l.favorite.replace('-','→')}は成立`);else if(l.actual_line_rank)parts.push(`本命LINEは外れたが、実際の1・2着はLINE #${l.actual_line_rank}`);else parts.push('本命LINEは外れ、実際の1・2着は保存したLINE候補外');if(l.conditional_third_rank)parts.push(`実3着は条件付き #${l.conditional_third_rank}`);else parts.push('実3着の条件付き順位は保存なし');parts.push(fr===1?'FREEは#1的中':fr?`FREEは#${fr}でTop12内`:'FREEはTop12外');return parts.join('。')+'。'}
function openResultV2(v,r){explicitTab=true;const freeze=v.eligibility?.race_prediction?.timestamp;$('#detailBody').innerHTML=`${detailBack()}<section class="result-hero"><small>① 実際</small><h1>${r.venue}${r.race_no}R　${tm(r)}</h1><strong>結果 ${v.actual.trifecta}</strong><b>3連単 ${yen(v.actual.payout)}</b>${resultSummary(v)}</section><section class="detail-section prediction-summary"><small>② 予想時</small><h2>発走前の予想サマリー</h2><div class="fact-grid"><span>並び <b>${lineup(r)}</b></span><span>型 <b>${r.formation}</b></span><span>PURE <b>${r.pure_score??'—'} ${r.pure_grade||''}</b></span><span>レース買い度 <b>${r.buy_score??'—'} ${r.buy_grade||''}</b></span><span>読みやすさ <b>${r.race_predictability_score??'—'}</b></span><span>予想確定 <b>${freeze?new Date(freeze).toLocaleString('ja-JP'):'当時の記録なし'}</b></span></div><p>${qualification(v)}</p></section><section class="detail-section flow-v2"><small>③ 予想時</small><h2>AIはこう読んでた</h2><p>${esc(flow(r))}</p></section>${flowFacts(v)}${fitDetail(r,v)}${lineDetail(r,v)}${freeDetail(r,v)}${actualTicketDetail(r,v)}<section class="detail-section buy-detail"><h2>発走前のBUY評価</h2><h3>LINE BUY</h3><div class="buy-list">${buyRows(r,v,'LINE_MODEL')}</div><h3>FREE BUY</h3><div class="buy-list">${buyRows(r,v,'FREE_ORDER_MODEL')}</div><small>${modelNote(v,'ticket_buy_v3')}</small></section><section class="detail-section read-summary"><h2>どこまで読めてた？</h2><p>${esc(readSummary(v))}</p><small>保存済みValidationのLINE順位・3着順位・FREE順位だけから表示しています。</small></section>${detailBack()}`;$('#detail').showModal();document.querySelectorAll('.back-results').forEach(b=>b.onclick=()=>{$('#detail').close();history.replaceState(null,'',`?tab=results&date=${selectedDate}`)});history.replaceState(null,'',`?tab=results&date=${selectedDate}&race=${encodeURIComponent(v.race_id)}`)}
const openResultV2Base=openResultV2;openResultV2=function(v,r){openResultV2Base(v,r);const key=lines(r).flatMap(l=>third(r,l.event)).find(x=>x.ticket_key)?.ticket_key,version=key?.split('|')?.[2]||'当時のversion記録なし',grid=document.querySelector('.prediction-summary .fact-grid');if(grid)grid.insertAdjacentHTML('beforeend',`<span>予想version <b>${esc(version)}</b></span>`)};openResult=openResultV2;
const metric=(l,x)=>`<article><span>${l}</span><b>${x?.n?(100*x.rate).toFixed(1)+'%':'—'}</b><small>${x?.hits??0} / ${x?.n??0}</small></article>`;function cumulativeView(){const v=cumulative.virtual_purchase,strategies=v?.periods?.[vpPeriod];if(!strategies)return`<section class="history"><div class="warning">累積仮想成績はまだありません。</div></section>`;const line=strategies.MAIN_LINE_TOP3,free=strategies.FREE_TOP12,label={DAYS_7:'7日',DAYS_30:'30日',ALL_TIME:'全期間'};return`<section class="history cumulative-vp"><div class="period-tabs">${Object.entries(label).map(([k,x])=>`<button class="${vpPeriod===k?'active':''}" onclick="setVpPeriod('${k}')">${x}</button>`).join('')}</div><div class="warning">100円均等のモデル比較用仮想成績です。実購入成績ではありません。</div><h2>${label[vpPeriod]}のメイン戦略</h2><div class="virtual-grid">${vpMainCard('LINE 本命3点',line,'本命LINE × 3着上位3点')}${vpMainCard('FREE Top12',free,'発走前FREE Top12')}</div></section>${vpComparison(strategies,vpCumTab,'cumulative')}`}
function syncLegacyResultAliases(){dayData=resultDayData;selectedDate=resultSelectedDate}
function renderResults(){if(currentPage!=='results'||!resultDayData||resultDayData.date!==resultSelectedDate)return;syncLegacyResultAliases();const dates=historyIndex.available_dates.map(x=>x.date),pos=dates.indexOf(resultSelectedDate),d=new Date(resultSelectedDate+'T00:00:00');$('#dateTitle').textContent=`${d.getMonth()+1}月${d.getDate()}日`;$('#prevDate').disabled=pos<0||pos===dates.length-1;$('#nextDate').disabled=pos<=0;$('#dateSelect').value=resultSelectedDate;const races=resultDayData.races||[],vs=[...(resultDayData.validations||[])].sort((a,b)=>new Date(races.find(r=>r.id===a.race_id)?.start_time||0)-new Date(races.find(r=>r.id===b.race_id)?.start_time||0));$('#count').textContent=vs.length+'レース';const empty=resultSelectedDate===todayData.date?'まだ本日の検証結果はありません':'この日の検証データはありません。';$('#content').innerHTML=virtualPurchaseView()+(vs.length?vs.map(v=>resultCard(v,races.find(r=>r.id===v.race_id))).join(''):`<div class="empty">${empty}</div>`);document.querySelectorAll('[data-result]').forEach(el=>el.onclick=()=>{const v=resultDayData.validations.find(x=>x.race_id===el.dataset.result),r=races.find(x=>x.id===v.race_id);openResultV2(v,r)})}
async function loadResultDay(date,{race=null,updateUrl=true}={}){resultSelectedDate=date;syncLegacyResultAliases();const requestId=++resultRequestSerial;if(resultAbortController)resultAbortController.abort();const controller=new AbortController();resultAbortController=controller;$('#dateStatus').textContent='読み込み中…';try{const res=await fetch(`./data/days/${date}.json`,{cache:'no-store',signal:controller.signal});if(!res.ok)throw Error(`HTTP ${res.status}`);const data=await res.json();if(requestId!==resultRequestSerial||date!==resultSelectedDate)return false;if(data.date!==resultSelectedDate)throw Error(`DATE_MISMATCH ${data.date} != ${resultSelectedDate}`);resultDayData=data;syncLegacyResultAliases();$('#dateStatus').textContent='';if(updateUrl&&currentPage==='results')history.replaceState(null,'',`?tab=results&date=${date}${race?'&race='+encodeURIComponent(race):''}`);if(currentPage==='results'){renderResults();if(race){const v=resultDayData.validations?.find(x=>x.race_id===race),r=resultDayData.races?.find(x=>x.id===race);if(v&&r)openResultV2(v,r)}}return true}catch(e){if(e.name==='AbortError'||requestId!==resultRequestSerial)return false;if(date!==resultSelectedDate)return false;resultDayData={date,races:[],validations:[],virtual_purchase:null};syncLegacyResultAliases();$('#dateStatus').textContent=e.message.startsWith('DATE_MISMATCH')?'日付データが一致しないため表示を止めました':'この日の検証データはありません';if(currentPage==='results')renderResults();return false}}
function renderUpcoming(){const now=new Date(),s=$('#sort').value;let xs=(todayData.races||[]).filter(r=>new Date(r.start_time)>now);xs.sort(s==='start'?(a,b)=>new Date(a.start_time)-new Date(b.start_time):s==='pure'?(a,b)=>(b.pure_score??-1)-(a.pure_score??-1):(a,b)=>(b.buy_score??-1)-(a.buy_score??-1));const confirmed=todayData.counts?.prediction_freeze_confirmed??todayData.races.filter(r=>r.quality_status==='PREDICTION_FROZEN').length,incomplete=todayData.counts?.prediction_incomplete??todayData.races.length-confirmed;$('#count').textContent=`予想確定 ${confirmed}R / 未確定 ${incomplete}R`;$('#content').innerHTML=xs.length?xs.map(raceCard).join(''):'<div class="empty">未発走対象レースはありません。</div>'}
function openUpcomingFromTarget(target){const card=target.closest?.('[data-race]');if(currentPage!=='upcoming'||!card)return;const race=todayData.races.find(x=>String(x.id)===String(card.dataset.race));if(race)openPredictionDetail(race)}
$('#content').addEventListener('click',e=>openUpcomingFromTarget(e.target));
$('#content').addEventListener('keydown',e=>{if(currentPage!=='upcoming'||(e.key!=='Enter'&&e.key!==' '))return;const card=e.target.closest?.('[data-race]');if(!card)return;e.preventDefault();openUpcomingFromTarget(card)});
function renderCurrentPage(){page=currentPage;$('#sortLabel').hidden=currentPage!=='upcoming';$('#dateNav').hidden=currentPage!=='results';if(currentPage==='upcoming')renderUpcoming();else if(currentPage==='results')renderResults();else{$('#count').textContent=(cumulativeData.prospective_valid_races??0)+'レース';$('#content').innerHTML=cumulativeView()}}

function replayCard(x,r){const a=x.reference_result?.result,label=x.classification==='REPLAY'?'研究用REPLAY':'REPLAYなし';return`<article class="result-card replay-card" data-replay="${x.race_id}"><div class="head"><b>${r?.venue||''} ${r?.race_no||''}R</b><time>${r?tm(r):'—'}</time></div><div class="actual"><strong>${a?`結果 ${a.trifecta}`:'参考結果 未取得'}</strong>${a?`<b>3連単 ${yen(a.payout)}</b>`:''}</div><div class="answer-mini"><p><b>${label}</b>　${x.status==='REPLAY_GENERATED'?'発走前保存データだけで生成':'予想は生成していません'}</p></div><small class="human-status">${esc(x.notice||'正式成績には含めません')}</small><button class="more">詳しく見る</button></article>`}
function replaySummaryView(){const x=resultDayData?.replay_research;if(!x)return'';return`<section class="virtual-score replay-summary"><header><div><small>正式ROIとは別集計</small><h2>研究用REPLAY</h2></div><b>${x.replay_generated} / ${x.replay_targets}R 生成</b></header><div class="fact-grid"><span>Top1 <b>${x.free_top1_hits}件</b></span><span>Top3 <b>${x.free_top3_hits}件</b></span><span>Top5 <b>${x.free_top5_hits}件</b></span><span>NO_REPLAY <b>${x.no_replay}R</b></span></div><small>LIVEの的中率・仮想購入・累積ROIには合算していません。</small></section>`}
function replayLineRows(p){return(p?.line_model?.lines||[]).map(l=>`<article><b>#${l.line_rank??'—'} ${l.event}</b>${(l.conditional_third_candidates||[]).map(c=>`<span>#${c.rank} ${carMark(c.rider_number)}　3着評価シェア ${c.uncalibrated_third_share==null?'—':(c.uncalibrated_third_share*100).toFixed(1)+'%'}</span>`).join('')}</article>`).join('')||'<p>LINE出力はありません。</p>'}
function openReplay(x,r){const a=x.reference_result?.result,p=x.prediction,free=p?.free_model?.top12||[],n=p?.race_flow_narrative?.text||p?.race_flow_narrative?.narrative||p?.scenarios?.MAIN?.summary||'保存された展開文章はありません。';$('#detailBody').innerHTML=`${detailBack()}<section class="result-hero"><small>${x.classification==='REPLAY'?'研究用REPLAY':'NO_REPLAY'}</small><h1>${r?.venue||''}${r?.race_no||''}R　${r?tm(r):''}</h1>${a?`<strong>結果 ${a.trifecta}</strong><b>3連単 ${yen(a.payout)}</b>`:'<strong>参考結果はまだありません</strong>'}</section>${x.status==='REPLAY_GENERATED'?`<section class="detail-section"><h2>研究用REPLAY Prediction</h2><p class="warning">発走後生成だが、発走前保存データのみ使用</p><div class="fact-grid"><span>Evidence cutoff <b>${x.evidence_cutoff?new Date(x.evidence_cutoff).toLocaleString('ja-JP'):'—'}</b></span><span>Version <b>${esc(p?.version||'—')}</b></span></div></section><section class="detail-section"><h2>AI展開予想</h2><p>${esc(n)}</p></section><section class="detail-section"><h2>LINE MODEL</h2><div class="line-model-detail">${replayLineRows(p)}</div></section><section class="detail-section"><h2>FREE Top12</h2>${free.map(z=>`<p>#${z.rank}　${z.trifecta}　全体評価シェア ${z.uncalibrated_share==null?'—':(z.uncalibrated_share*100).toFixed(1)+'%'}</p>`).join('')}</section>`:`<section class="detail-section warning"><h2>${x.status}</h2><p>${esc(x.notice||'発走前Evidence Bundleがないため予想を生成しません。')}</p></section>`}<section class="eligibility-box"><b>正式Validation・仮想購入・累積ROIの対象外</b></section>${detailBack()}`;$('#detail').showModal();document.querySelectorAll('.back-results').forEach(b=>b.onclick=()=>{$('#detail').close();history.replaceState(null,'',`?tab=results&date=${resultSelectedDate}`)});history.replaceState(null,'',`?tab=results&date=${resultSelectedDate}&race=${encodeURIComponent(x.race_id)}`)}
renderResults=function(){if(currentPage!=='results'||!resultDayData||resultDayData.date!==resultSelectedDate)return;syncLegacyResultAliases();const dates=historyIndex.available_dates.map(x=>x.date),pos=dates.indexOf(resultSelectedDate),d=new Date(resultSelectedDate+'T00:00:00');$('#dateTitle').textContent=`${d.getMonth()+1}月${d.getDate()}日`;$('#prevDate').disabled=pos<0||pos===dates.length-1;$('#nextDate').disabled=pos<=0;$('#dateSelect').value=resultSelectedDate;const races=resultDayData.races||[],vs=[...(resultDayData.validations||[])].sort((a,b)=>new Date(races.find(r=>r.id===a.race_id)?.start_time||0)-new Date(races.find(r=>r.id===b.race_id)?.start_time||0)),replays=[...(resultDayData.replay_records||[])].filter(x=>x.reference_result||x.classification==='REPLAY');$('#count').textContent=`LIVE ${vs.length}R / REPLAY・参考 ${replays.length}R`;const empty=!vs.length&&!replays?(resultSelectedDate===todayData.date?'まだ本日の検証結果はありません':'この日の検証データはありません。'):'';$('#content').innerHTML=virtualPurchaseView()+replaySummaryView()+vs.map(v=>resultCard(v,races.find(r=>r.id===v.race_id))).join('')+replays.map(x=>replayCard(x,races.find(r=>r.id===x.race_id))).join('')+(empty?`<div class="empty">${empty}</div>`:'');document.querySelectorAll('[data-result]').forEach(el=>el.onclick=()=>{const v=resultDayData.validations.find(x=>x.race_id===el.dataset.result),r=races.find(x=>x.id===v.race_id);openResultV2(v,r)});document.querySelectorAll('[data-replay]').forEach(el=>el.onclick=()=>{const x=resultDayData.replay_records.find(v=>v.race_id===el.dataset.replay),r=races.find(v=>v.id===x.race_id);openReplay(x,r)})}
function activatePage(name){currentPage=name;page=name;$('#content').replaceChildren();$('#dateNav').hidden=name!=='results';$('#dateNav').style.display=name==='results'?'grid':'none';$('#sortLabel').hidden=name!=='upcoming';$('#sortLabel').style.display=name==='upcoming'?'':'none';document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===name))}
async function init(){try{const [t,h,c]=await Promise.all(['today.json','history_index.json','cumulative.json'].map(async n=>{const r=await fetch('./data/'+n,{cache:'no-store'});if(!r.ok)throw Error(`${n} HTTP ${r.status}`);return r.json()}));todayData=t;historyIndex=h;cumulativeData=c;today=t;index=h;cumulative=c;const dates=historyIndex.available_dates.map(x=>x.date);$('#dateSelect').innerHTML=dates.map(d=>`<option value="${d}">${d}</option>`).join('');const params=new URLSearchParams(location.search),explicitResults=params.get('tab')==='results',requestedDate=params.get('date'),requestedRace=params.get('race');explicitTab=explicitResults;if(explicitResults){activatePage('results');resultSelectedDate=requestedDate||todayData.date;await loadResultDay(resultSelectedDate,{race:requestedRace,updateUrl:true})}else{activatePage('upcoming');history.replaceState(null,'',requestedRace?`${location.pathname}?race=${encodeURIComponent(requestedRace)}`:location.pathname);renderCurrentPage();if(requestedRace){const race=todayData.races.find(x=>String(x.id)===String(requestedRace));if(race)openPredictionDetail(race,{updateUrl:false})}}}catch(e){$('#count').textContent='ERROR';$('#content').innerHTML=`<div class="load-error">DATA LOAD ERROR<br>${esc(e.message)}</div>`}}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=async()=>{const target=b.dataset.page;explicitTab=target==='results';activatePage(target);if(target==='upcoming'){history.replaceState(null,'',location.pathname);renderUpcoming()}else if(target==='results'){resultSelectedDate=todayData.date;resultDayData=null;syncLegacyResultAliases();await loadResultDay(resultSelectedDate,{updateUrl:true})}else{history.replaceState(null,'',`?tab=cumulative`);renderCurrentPage()}});$('#sort').onchange=()=>{if(currentPage==='upcoming')renderUpcoming()};$('#dateSelect').onchange=e=>{if(currentPage==='results')loadResultDay(e.target.value)};$('#prevDate').onclick=()=>{if(currentPage!=='results')return;const a=historyIndex.available_dates.map(x=>x.date),i=a.indexOf(resultSelectedDate);if(i<a.length-1)loadResultDay(a[i+1])};$('#nextDate').onclick=()=>{if(currentPage!=='results')return;const a=historyIndex.available_dates.map(x=>x.date),i=a.indexOf(resultSelectedDate);if(i>0)loadResultDay(a[i-1])};$('#todayDate').onclick=()=>{if(currentPage==='results')loadResultDay(todayData.date)};$('.close').onclick=()=>{if(currentPage==='upcoming'&&new URLSearchParams(location.search).has('race'))history.back();else{$('#detail').close();history.replaceState(null,'',currentPage==='results'?`?tab=results&date=${resultSelectedDate}`:location.pathname)}};$('#detail').addEventListener('close',()=>{if(!suppressDetailCloseHistory&&currentPage==='upcoming'&&new URLSearchParams(location.search).has('race'))history.back();suppressDetailCloseHistory=false});window.addEventListener('popstate',()=>{if(currentPage!=='upcoming')return;const raceId=new URLSearchParams(location.search).get('race');if(raceId){const race=todayData.races.find(x=>String(x.id)===String(raceId));if(race)openPredictionDetail(race,{updateUrl:false})}else if($('#detail').open){suppressDetailCloseHistory=true;$('#detail').close()}});init();
